'use strict';
const games={easy:new Adventure.Game('easy'),medium:new Adventure.Game('medium'),sloth:new Adventure.SlothGame()};
const levelNames={easy:'Easy',medium:'Medium',sloth:'Mentally challenged mode'};
function restoreLevel(data,level){return level==='sloth'?Adventure.SlothGame.restore(data):Adventure.Game.restore(data,level);}
let storageAvailable=true;let selectedLevel='easy';
try{const legacy=JSON.parse(localStorage.getItem('goonies-levels-v1')||'null');for(const level of Object.keys(games)){const saved=JSON.parse(localStorage.getItem('goonies-save-'+level)||'null')||legacy?.[level];if(saved)games[level]=restoreLevel(saved,level);}const active=localStorage.getItem('goonies-active-level')||legacy?.active;selectedLevel=games[active]?active:'easy';}catch{storageAvailable=false;}
let game=games[selectedLevel];let historyIndex=game.history.length;let draft='';let speakingButton=null;let narration=null;
const $=id=>document.getElementById(id);
function stopNarration(){const previous=speakingButton;speakingButton=null;narration=null;if('speechSynthesis' in window)window.speechSynthesis.cancel();if(previous){previous.textContent='Read aloud';previous.setAttribute('aria-pressed','false');previous.setAttribute('aria-label','Read this passage aloud');}}
function readPassage(text,button){if(speakingButton===button){stopNarration();return;}stopNarration();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=.95;const voices=window.speechSynthesis.getVoices();const voice=voices.find(v=>v.lang==='en-US'&&v.localService)||voices.find(v=>v.lang.startsWith('en'));if(voice)utterance.voice=voice;narration=utterance;speakingButton=button;button.textContent='Stop reading';button.setAttribute('aria-pressed','true');button.setAttribute('aria-label','Stop reading this passage');const finish=()=>{if(narration!==utterance)return;narration=null;speakingButton=null;button.textContent='Read aloud';button.setAttribute('aria-pressed','false');button.setAttribute('aria-label','Read this passage aloud');};utterance.onend=finish;utterance.onerror=e=>{finish();if(!['canceled','interrupted'].includes(e.error)){button.textContent='Voice unavailable';button.title='Your browser could not start its voice. Try again or use a browser with text-to-speech support.';}};try{window.speechSynthesis.speak(utterance);}catch{finish();button.textContent='Voice unavailable';}}
function append(result,command,record=true){if(record)game.transcript.push({result:{...result,room:result.room||game.room},command});const entry=document.createElement('div');entry.className='entry'+(result.kind==='victory'?' victory':'');if(command){const echo=document.createElement('p');echo.className='command-echo';echo.textContent='> '+command;entry.append(echo);}const row=document.createElement('div');row.className='passage-controls';const roomName=game.rooms[result.room||game.room]?.name||game.current().name;if(result.heading){const h=document.createElement('p');h.className='room-heading';h.textContent=roomName;row.append(h);}const read=document.createElement('button');read.type='button';read.className='read-aloud';read.textContent='Read aloud';read.setAttribute('aria-pressed','false');read.setAttribute('aria-label','Read this passage aloud');if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){read.disabled=true;read.textContent='Voice unavailable';read.title='Read aloud needs a browser with built-in text-to-speech support.';}else read.onclick=()=>readPassage((result.heading?roomName+'\n':'')+result.lines.join('\n\n'),read);row.append(read);entry.append(row);for(const line of result.lines){const p=document.createElement('p');p.textContent=line;p.className=result.kind==='success'?'success':result.kind==='system'?'system':'';entry.append(p);}$('log').append(entry);$('log').scrollTop=$('log').scrollHeight;}
function render(){renderLevels();const r=game.current();$('room-title').textContent=r.name;$('chapter').textContent='CHAPTER '+['','I','II','III','IV'][r.chapter];document.querySelector('.adventure>.eyebrow>span:last-child').textContent=r.area;$('turns').textContent=game.moves+' move'+(game.moves===1?'':'s');$('explored').textContent=game.visited.size+' / '+Object.keys(game.rooms).length;$('pack-count').textContent=game.inventory.length+' item'+(game.inventory.length===1?'':'s');$('exits-label').textContent='Exits: '+Object.keys(r.exits).join(', ');document.querySelectorAll('.compass button').forEach(b=>b.classList.toggle('available',!!r.exits[b.dataset.command]));$('inventory').replaceChildren();if(!game.inventory.length){const e=document.createElement('span');e.className='empty-pack';e.textContent='Empty pockets. Big plans.';$('inventory').append(e);}else game.inventory.forEach(id=>{const b=document.createElement('button');b.className='item-chip';b.textContent=Adventure.items[id].name;b.title='Examine '+Adventure.items[id].name;b.onclick=()=>execute('examine '+Adventure.items[id].name);$('inventory').append(b);});renderMap();}
function renderMap(){const ns='http://www.w3.org/2000/svg',map=$('map');map.replaceChildren();const title=document.createElementNS(ns,'title');title.id='map-label';title.textContent='Discovered locations. Current location: '+game.current().name+'. '+game.visited.size+' places visited.';map.append(title);const pos=r=>({x:45+r.x*88,y:42+r.y*86});const paths=new Set();for(const id of game.visited){const r=game.rooms[id],a=pos(r);for(const to of Object.values(r.exits)){if(!game.visited.has(to))continue;const key=[id,to].sort().join('|');if(paths.has(key))continue;paths.add(key);const b=pos(game.rooms[to]);const line=document.createElementNS(ns,'line');for(const [k,v] of Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#66746c','stroke-width':2}))line.setAttribute(k,v);map.append(line);}}
for(const id of game.visited){const r=game.rooms[id],p=pos(r),active=id===game.room;const g=document.createElementNS(ns,'g');const c=document.createElementNS(ns,'circle');for(const [k,v] of Object.entries({cx:p.x,cy:p.y,r:active?10:7,fill:active?'#e8b86a':'#182125',stroke:active?'#e8b86a':'#a1ada8','stroke-width':2}))c.setAttribute(k,v);if(active){const halo=document.createElementNS(ns,'circle');for(const [k,v] of Object.entries({cx:p.x,cy:p.y,r:17,fill:'none',stroke:'#e8b86a','stroke-opacity':.3}))halo.setAttribute(k,v);g.append(halo);}g.append(c);const text=document.createElementNS(ns,'text');text.setAttribute('x',p.x);text.setAttribute('y',p.y+31);text.setAttribute('text-anchor','middle');text.setAttribute('class',active?'active-label':'node-title');r.short.split(' ').forEach((word,i,arr)=>{if(arr.length<2){text.textContent=word;return;}const span=document.createElementNS(ns,'tspan');span.setAttribute('x',p.x);span.setAttribute('dy',i?15:0);span.textContent=word;text.append(span);});g.append(text);map.append(g);}$('map-empty').hidden=game.visited.size>1;}
function persist(){try{localStorage.setItem('goonies-save-'+game.level,JSON.stringify(game.save()));localStorage.setItem('goonies-active-level',game.level);}catch{storageAvailable=false;}const note=$('level-save-note');if(note)note.textContent=storageAvailable?'Each level saves its own progress on this device.':'Each level keeps its own progress while this page stays open.';}
function renderTranscript(){ $('log').replaceChildren();if(game.transcript.length)game.transcript.forEach(t=>append(t.result,t.command,false));else append({lines:game.describe(),heading:true,room:game.room});}
function switchLevel(level){if(!games[level]||game.level===level)return;stopNarration();persist();try{const saved=JSON.parse(localStorage.getItem('goonies-save-'+level)||'null');if(saved)games[level]=restoreLevel(saved,level);}catch{}game=games[level];historyIndex=game.history.length;draft='';$('command').value='';renderTranscript();render();persist();}
function renderLevels(){document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.level===game.level)));$('level-description').textContent={easy:'Easy · The original adventure',medium:'Medium · Four new pirate puzzles',sloth:'Sloth · A first day of freedom'}[game.level];document.querySelector('.objective p').textContent=game.level==='sloth'?'Find your feet. Help your friends. Bring the Fratellis to justice.':'Find One-Eyed Willy’s treasure. Save the Goon Docks.';document.querySelector('.shortcuts>span').textContent=game.level==='sloth'?'Try “take all” or “go south”':'Try “take map” or “go south”';}
function execute(raw){if(typeof raw!=='string'||!raw.trim())return game.snapshot();const result=game.run(raw);append(result,raw);render();persist();historyIndex=game.history.length;$('command').value='';draft='';return {response:result.lines,...game.snapshot()};}
$('command-form').addEventListener('submit',e=>{e.preventDefault();execute($('command').value);});document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>execute(b.dataset.command)));
$('command').addEventListener('keydown',e=>{if(e.key==='ArrowUp'){e.preventDefault();if(historyIndex===game.history.length)draft=e.target.value;historyIndex=Math.max(0,historyIndex-1);e.target.value=game.history[historyIndex]||draft;}if(e.key==='ArrowDown'){e.preventDefault();historyIndex=Math.min(game.history.length,historyIndex+1);e.target.value=game.history[historyIndex]||draft;}});
$('restart').onclick=()=>{$('restart-dialog').querySelector('h2').textContent='Restart '+levelNames[game.level]+'?';$('restart-dialog').showModal();};
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>switchLevel(b.dataset.level));$('cancel-restart').onclick=()=>$('restart-dialog').close();$('confirm-restart').onclick=()=>{stopNarration();game=game.level==='sloth'?new Adventure.SlothGame():new Adventure.Game(game.level);games[game.level]=game;historyIndex=0;draft='';$('log').replaceChildren();$('command').value='';append({lines:game.describe(),heading:true});render();persist();$('restart-dialog').close();$('command').focus();};
renderTranscript();render();persist();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'perform_adventure_command',title:'Play the text adventure',description:'Perform one command in the current Goonies adventure, such as look, take map, use rope, or go south. Changes the same game shown on the page.',inputSchema:{type:'object',properties:{command:{type:'string',minLength:1,maxLength:160}},required:['command'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.command!=='string'||!input.command.trim()||input.command.length>160||Object.keys(input).some(k=>k!=='command'))throw new Error('Provide a command of 1–160 characters.');return execute(input.command);}})).catch(()=>{});}catch{}}
