(function(root){
'use strict';
const rooms={
 attic:{name:'The Walsh attic',short:'Walsh attic',x:0,y:0,chapter:1,area:'THE GOON DOCKS',description:'Rain taps against the attic window. Tomorrow, the developers take the Goon Docks. Today, Mikey has other plans.\n\nBetween a stack of old adventure magazines and a dusty globe lies a brittle pirate map. A brass medallion rests beside it. Mouth leans over your shoulder. “Please tell me this beats packing boxes.”',exits:{south:'street'},items:['map','medallion']},
 street:{name:'The Goon Docks',short:'Goon Docks',x:0,y:1,chapter:1,area:'THE GOON DOCKS',description:'You pedal through rain-slick streets with Mikey, Mouth, Data, and Chunk. Beyond the last houses, an abandoned restaurant crouches on the headland.\n\nData has left a flashlight and a crowbar beside the bike rack. “Standard expedition equipment. Mostly tested.”',exits:{north:'attic',east:'shack'},items:['flashlight','crowbar']},
 shack:{name:'The old restaurant',short:'Restaurant',x:1,y:1,chapter:1,area:'THE GOON DOCKS',description:'The restaurant smells of salt, cold grease, and trouble. Somewhere upstairs, a Fratelli slams a door. Chunk freezes halfway through a snack.\n\nA heavy floor hatch is nailed shut. Scratches around its edge suggest somebody else wanted to get below.',exits:{west:'street',south:'cellar'},items:[]},
 cellar:{name:'The hidden cellar',short:'Cellar',x:1,y:2,chapter:2,area:'BENEATH ASTORIA',description:'The hatch drops you into a cellar that predates the restaurant by centuries. A cold draft slips through a broken fireplace.\n\nMikey points at a skull carved into the stone. Beneath it: “The sun admits the sailor.” A passage leads south, into absolute darkness.',exits:{north:'shack',south:'tunnel',east:'chart'},items:[]},
 chart:{name:'The chart room',short:'Chart room',x:2,y:2,chapter:2,area:'BENEATH ASTORIA',description:'A stone desk stands beneath a faded painting of One-Eyed Willy. You brush grit from a weathered inscription: “When bones sing, climb from C to E to G. Then cross without touching the sea.”\n\nMouth reads it twice. “Pirates. Always with the homework.”',exits:{west:'cellar'},items:['doubloon']},
 tunnel:{name:'The smugglers’ tunnel',short:'Tunnel',x:1,y:3,chapter:2,area:'BENEATH ASTORIA',description:'Your flashlight catches boot prints, old timber braces, and tiny streams running through the floor. The ocean thunders somewhere below.\n\nTo the west you hear falling water. To the east, pipes rattle like a giant trying to clear its throat.',exits:{north:'cellar',west:'well',east:'pipes'},items:[]},
 well:{name:'The wishing well',short:'Wishing well',x:0,y:3,chapter:2,area:'BENEATH ASTORIA',description:'Coins glitter under shallow water. Far above, daylight falls through a round opening. These are somebody’s wishes. You leave them where they are.\n\nA small bone flute is wedged between two stones. On the wall, a carving shows a musician holding it beside an enormous organ.',exits:{east:'tunnel'},items:['flute']},
 pipes:{name:'The pipe chamber',short:'Pipe chamber',x:2,y:3,chapter:2,area:'BENEATH ASTORIA',description:'Steam hisses from a forest of old pipes. Data makes a heroic attempt to understand the plumbing. The resulting shower answers his first three questions.\n\nA coil of sturdy rope hangs from a dry bracket. An arch to the east carries the same musician symbol you saw on the map.',exits:{west:'tunnel',east:'organ'},items:['rope']},
 organ:{name:'The bone organ',short:'Bone organ',x:3,y:3,chapter:2,area:'BENEATH ASTORIA',description:'An organ made of bones fills the chamber. Three keys are marked C, E, and G. A tiny flute-shaped socket sits above them.\n\nBeyond the instrument, a stone door seals the southern passage. Andy studies the keys. “We need the starting note—and something to wake it up.”',exits:{west:'pipes',south:'bridge'},items:[]},
 bridge:{name:'The broken crossing',short:'Crossing',x:3,y:4,chapter:3,area:'ONE-EYED WILLY’S TRAIL',description:'The floor ends at a split in the rock. Black water churns below. An iron ring waits on this side; a stone post stands on the far bank.\n\nA narrow ledge runs west. Across the gap to the south, a cavern glimmers with reflected light. Mikey looks at your backpack. “There has to be a way.”',exits:{north:'organ',west:'grotto',south:'lagoon'},items:[]},
 grotto:{name:'The crystal grotto',short:'Crystal grotto',x:2,y:4,chapter:3,area:'ONE-EYED WILLY’S TRAIL',description:'Green crystals turn your flashlight beam into a thousand tiny stars. A worn emerald lies loose in the sand.\n\nChunk finds a pirate’s boot, decides it is not edible, and puts it back. This quiet pocket of the cave is a good place to catch your breath.',exits:{east:'bridge'},items:['emerald']},
 lagoon:{name:'The underground lagoon',short:'Lagoon',x:3,y:5,chapter:3,area:'ONE-EYED WILLY’S TRAIL',description:'A pirate ship rises from the mist. The Inferno. Its masts disappear into the darkness, and its lanterns glow as if somebody lit them yesterday.\n\nA gangplank reaches the eastern shore. Behind you, your rope crossing holds firm. Somewhere in the tunnels, the Fratellis shout your names.',exits:{north:'bridge',east:'deck'},items:[]},
 deck:{name:'Aboard the Inferno',short:'Inferno deck',x:4,y:5,chapter:3,area:'THE INFERNO',description:'Your shoes creak on the deck of the Inferno. The captain’s cabin waits to the north. To the east, a narrow sea passage promises daylight.\n\nSloth appears on the gangplank with a triumphant grin. He is holding off the Fratellis. “Go! Find treasure!” There is still time.',exits:{west:'lagoon',north:'cabin',east:'beach'},items:[]},
 cabin:{name:'One-Eyed Willy’s cabin',short:'Willy’s cabin',x:4,y:4,chapter:3,area:'THE INFERNO',description:'One-Eyed Willy sits at the head of a long table, guarding his last feast. You nod to the old captain.\n\nA small chest bears a coin-shaped lock. Beside it, a separate pile of gold balances a delicate mechanism. Mikey whispers, “Leave the gold on the scales. Willy earned that.”',exits:{south:'deck'},items:['treasure']},
 beach:{name:'Daylight at last',short:'The beach',x:5,y:5,chapter:4,area:'THE PACIFIC COAST',description:'You emerge onto a wind-torn beach. The whole gang tumbles out after you. Sirens and your parents’ voices carry across the sand.\n\nBehind you, the sea tunnel is still open. Ahead, the future of the Goon Docks hangs on what you managed to bring back.',exits:{west:'deck'},items:[]}
};
const items={map:{name:'pirate map',aliases:['map','pirate map'],description:'A map signed by One-Eyed Willy. The sun opens the way. A musician wakes the bones. A sailor ties the crossing. Turn it over: “The captain accepts his own coin.”'},medallion:{name:'sun medallion',aliases:['medallion','sun medallion','brass medallion'],description:'A brass disk engraved with a smiling sun. It would fit the skull carving in the cellar.'},flashlight:{name:'flashlight',aliases:['flashlight','torch','light'],description:'Data’s flashlight. Turn it on with “use flashlight” before venturing into darkness.'},crowbar:{name:'crowbar',aliases:['crowbar','bar'],description:'A sturdy iron crowbar. Perfect for prying open the restaurant’s nailed hatch.'},doubloon:{name:'doubloon',aliases:['doubloon','coin','pirate coin'],description:'A pirate coin stamped with Willy’s seal. The captain’s chest has a lock exactly this size.'},flute:{name:'bone flute',aliases:['flute','bone flute'],description:'Three holes, three notes. A flute-shaped socket on the bone organ might accept it.'},rope:{name:'rope',aliases:['rope','coil of rope'],description:'A long coil of sailor’s rope. Enough to rig a safe crossing over the gap.'},emerald:{name:'emerald',aliases:['emerald','gem'],description:'A bright green emerald. A bonus for your adventure—and possibly a new bicycle.'},treasure:{name:'pouch of jewels',aliases:['treasure','jewels','pouch','pouch of jewels','gems'],description:'A pouch of rubies and sapphires, safely separate from Willy’s booby-trapped gold. Enough to save your homes.'}};
const mediumRooms={...rooms,
 chart:{...rooms.chart,description:rooms.chart.description+'\n\nThree compass wheels guard a door to the north. A navigator’s verse reads: “First face the rising sun; next seek the pole star; last watch the setting sun.” Each wheel accepts north, south, east, or west. Use “set compass” followed by three directions.',exits:{west:'cellar',north:'tide'}},
 tide:{name:'The tideworks',short:'Tideworks',x:2,y:1,chapter:2,area:'BENEATH ASTORIA',description:'A forgotten tidal engine drives Willy’s traps. Three valves bear a moon, an anchor, and a sun. Their order matters: the wrong valve resets the mechanism, but causes no harm.\n\nA brass placard reads: “Night draws the tide. The sailor holds it. Dawn sends it onward.” Turn them one at a time with “turn valve [symbol]”. A gauge marked ORGAN PASSAGE trembles in the red.',exits:{south:'chart'},items:[]},
 well:{...rooms.well,description:'Coins glitter under shallow water. These are somebody’s wishes; you leave them alone. A bone flute sits behind a grille in the wall.\n\nA carving shows three waves rising from small to tall. Beside it: “Let the bells climb as the sea climbs.” A staircase leads north to a bell alcove.',exits:{east:'tunnel',north:'bells'}},
 bells:{name:'The bell alcove',short:'Bell alcove',x:0,y:2,chapter:2,area:'BENEATH ASTORIA',description:'Three bronze bells hang above the well. Bell 1 has a middle pitch. Bell 2 has a low pitch. Bell 3 has a high pitch. A cable connects them to the flute’s grille below.\n\nYou can try a sequence with “ring bells [three numbers]”. A wrong tune resets the cable safely. The waves beside the wishing well hint at the melody.',exits:{south:'well'},items:[]},
 pipes:{...rooms.pipes,description:rooms.pipes.description+'\n\nScalding steam blocks the eastern arch. A gauge points toward a tidal engine; this passage will need its pressure released upstream.'},
 cabin:{...rooms.cabin,description:'One-Eyed Willy sits at the head of his last feast. You nod respectfully. Leave the gold on his delicate balance alone.\n\nThe smaller jewel chest has its own weighing tray and a shutter covering its coin lock. A dial reads 0 through 9. An engraving says: “Set the burden still borne by the chest.” The ship’s cargo ledger may help. A door leads east to the sail loft.',exits:{south:'deck',east:'loft'}},
 loft:{name:'The sail loft',short:'Sail loft',x:5,y:4,chapter:3,area:'THE INFERNO',description:'Rotting canvas frames a desk stacked with shipping records. A brass counterweight lies beside the captain’s cargo ledger.\n\nThe ledger reads: “Chest and jewels: seven marks. Brass counterweight: three marks. Set the dial to the burden remaining after the counterweight takes its share.”\n\nA sketch shows the counterweight on the small chest’s tray. Willy’s gold is a separate mechanism. Mouth grins. “Finally, pirate math.”',exits:{west:'cabin'},items:['weight']}
};
items.weight={name:'brass counterweight',aliases:['weight','counterweight','brass counterweight'],description:'A brass counterweight weighing three marks. It belongs on the jewel chest’s weighing tray. The cargo ledger lists the chest’s total weight.'};
class Game{
 constructor(level='easy'){this.level=level==='medium'?'medium':'easy';this.rooms=this.level==='medium'?mediumRooms:rooms;this.room='attic';this.visited=new Set(['attic']);this.inventory=[];this.taken=new Set();this.flags={};this.moves=0;this.won=false;this.history=[];this.hints={};this.transcript=[];}
 current(){return this.rooms[this.room];}
 visibleItems(){return this.current().items.filter(i=>!this.taken.has(i)&&(i!=='treasure'||this.flags.chest)&&(this.level!=='medium'||i!=='flute'||this.flags.bells));}
 describe(){let description=this.current().description;if(this.level==='medium'){if(this.room==='well'&&this.flags.bells)description=description.replace('A bone flute sits behind a grille in the wall.','The flute niche is open; the bells have raised its grille.');if(this.room==='pipes'&&this.flags.tide)description=description.replace('Scalding steam blocks the eastern arch. A gauge points toward a tidal engine; this passage will need its pressure released upstream.','The tidal engine is vented. The gauge is green, and the eastern arch is clear.');if(this.room==='tide'&&this.flags.tide)description=description.replace('A gauge marked ORGAN PASSAGE trembles in the red.','The ORGAN PASSAGE gauge reads green. All three valves are aligned.');if(this.room==='chart'&&this.flags.compass)description+='\n\nThe compass wheels are aligned. The northern door stands open.';if(this.room==='bells'&&this.flags.bells)description+='\n\nThe cable is latched. The flute grille below is open.';if(this.room==='cabin'&&this.flags.balance)description+='\n\nThe tray is balanced at four marks. The shutter is open, exposing the chest’s coin lock.';}let lines=[description];if(this.visibleItems().length)lines.push('You see: '+this.visibleItems().map(i=>items[i].name).join(', ')+'.');lines.push('Exits: '+Object.keys(this.current().exits).join(', ')+'.');return lines;}
 identify(s){s=s.replace(/^(the|a|an) /,'').trim();return Object.keys(items).find(i=>items[i].aliases.includes(s));}
 available(i){return this.inventory.includes(i)||this.visibleItems().includes(i);}
 easyHint(){if(this.won)return 'You saved the Goon Docks! Explore any places you missed, or start a new adventure.';if(!this.inventory.includes('map'))return 'Start in the attic: “take map”. Read it for Willy’s clues.';if(!this.inventory.includes('medallion'))return 'The sun medallion in the attic is more than a souvenir. Take it.';if(!this.inventory.includes('crowbar'))return 'A crowbar and flashlight wait on the Goon Docks street. Take both.';if(!this.inventory.includes('flashlight'))return 'Pick up Data’s flashlight on the street. The passages below are dark.';if(!this.flags.hatch)return 'In the restaurant, “use crowbar” will open the floor hatch. Then go south.';if(!this.flags.sun)return 'In the cellar, “use medallion” on the skull carving to open the stone passage.';if(!this.flags.light)return 'Turn on your light with “use flashlight”. It won’t run out of batteries.';if(!this.inventory.includes('doubloon'))return 'The chart room is east of the cellar. Take the doubloon and read the inscription.';if(!this.inventory.includes('flute'))return 'The wishing well is west of the smugglers’ tunnel. Take the bone flute.';if(!this.inventory.includes('rope'))return 'There is rope in the pipe chamber, east of the tunnel. You’ll need it.';if(!this.flags.flute)return 'At the bone organ, “use flute” to wake the instrument.';if(!this.flags.organ)return 'The chart room inscription gives the sequence: “play C E G” at the organ.';if(!this.flags.rope)return 'Go south to the crossing, then “use rope”.';if(!this.flags.chest)return 'Cross south, board the ship to the east, and enter the cabin to the north. Use the doubloon on the chest.';if(!this.inventory.includes('treasure'))return 'In Willy’s cabin, “take treasure”. Leave the gold on the scales alone.';return 'From the ship’s deck, go east to the beach with the jewels. Your friends are waiting.';}
 hint(){if(this.level==='medium'&&!this.won){let key,clues;
 if(this.flags.sun&&this.flags.light&&this.inventory.includes('doubloon')&&!this.flags.compass){key='compass';clues=['There is a second door in the chart room. Its navigator’s verse gives three compass directions.','Sunrise and sunset name opposite directions. The pole star marks north.','At the chart room, type “set compass east north west”.'];}
 else if(this.flags.compass&&!this.flags.tide){key='tide';clues=['Explore north of the chart room. The tidal engine controls the steam in the pipe chamber.','Match each line of the placard to a symbol: night, a sailor’s hold, then dawn.','At the tideworks, turn the moon valve, then the anchor valve, then the sun valve. Use “turn valve moon” first.'];}
 else if(this.flags.tide&&!this.flags.bells){key='bells';clues=['The flute is behind a grille at the wishing well. Explore the bell alcove to its north.','The waves rise. Ring the bells from lowest pitch to highest, using their numbered labels.','At the bell alcove, type “ring bells 2 1 3”. Return south and take the flute.'];}
 else if(this.flags.rope&&this.inventory.includes('doubloon')&&!this.flags.balance){key='balance';clues=['The jewel chest has an extra lock. Look for the cargo ledger east of Willy’s cabin.','Take the brass counterweight from the sail loft, use it at the chest, and subtract its weight from the total in the ledger.','Take the counterweight in the loft. In the cabin: “use weight”, then “set balance 4”. Now use the doubloon.'];}
 if(key){const n=this.hints[key]||0;this.hints[key]=n+1;return 'MEDIUM HINT '+Math.min(n+1,3)+' / 3\n'+clues[Math.min(n,2)];}}
 return this.easyHint();}
 mediumCommand(cmd){const reply=(text,kind='normal')=>({lines:[text],kind,room:this.room});
 if(cmd==='help'||cmd==='commands')return {lines:['Easy’s movement and item commands still work. Medium adds four original puzzles: compass wheels, a tidal engine, pitched bells, and a cargo balance.','NEW COMMANDS\nset compass [three directions]\nturn valve [moon, anchor, or sun]\nring bells [three numbers]\nuse weight\nset balance [0–9]','Read the clues where you find each mechanism. “Hint” gives a nudge first; repeat it for stronger help. Wrong answers are safe to retry.','EXPLORATION\nlook · take all · examine [object] · read ledger · inventory · talk · use [item] · play [notes] · north / south / east / west'],kind:'system',room:this.room};
 if(/^set compass\b/.test(cmd)){if(this.room!=='chart')return reply('There are no compass wheels here.');if(this.flags.compass)return reply('The compass door is already open.');if(cmd.replace(/^set compass\s*/,'').replace(/[,\-]/g,' ').replace(/\s+/g,' ').trim()==='east north west'){this.flags.compass=true;return reply('You align sunrise, the pole star, and sunset. The compass wheels click into place. The tideworks door opens to the north.','success');}return reply('The wheels spring back. Use three full directions after “set compass”, following the navigator’s verse.');}
 if(/^turn(?: the)? valve\b/.test(cmd)){if(this.room!=='tide')return reply('There are no tidal valves here.');if(this.flags.tide)return reply('The engine is already vented. The eastern pipe passage is safe.');const symbol=cmd.replace(/^turn(?: the)? valve\s*/,'');if(!['moon','anchor','sun'].includes(symbol))return reply('Choose a named valve: moon, anchor, or sun.');const step=this.flags.valveStep||0;if(symbol!==['moon','anchor','sun'][step]){this.flags.valveStep=0;return reply('The valves clunk back to their starting positions. No harm done. Check the order in the brass placard.');}this.flags.valveStep=step+1;if(step===2){this.flags.tide=true;return reply('The last valve turns. Steam vents into a flooded shaft; the gauge settles into green. The path east from the pipe chamber is now safe.','success');}return reply('The '+symbol+' valve locks into place. '+(step+1)+' of 3 valves aligned.');}
 if(/^ring(?: the)? bells?\b/.test(cmd)){if(this.room!=='bells')return reply('The numbered bells are in the alcove above the wishing well.');if(this.flags.bells)return reply('The grille is already raised. The flute waits in the well below.');if(cmd.replace(/^ring(?: the)? bells?\s*/,'').replace(/[ ,\-]/g,'')==='213'){this.flags.bells=true;return reply('Low, middle, high. The bells climb like the carved waves. A cable pulls the well’s grille open. Go south to collect the flute.','success');}return reply('The cable catches, then relaxes. The grille remains closed. Match the waves’ ascent to the bells’ pitches.');}
 if(/^set (?:balance|dial)\b/.test(cmd)){if(this.room!=='cabin')return reply('The cargo balance dial is in Willy’s cabin.');if(this.flags.balance)return reply('The balance is already set correctly. The coin lock is exposed.');if(!this.flags.weight)return reply('The tray needs its brass counterweight before the dial can balance the chest.');if(/^set (?:balance|dial) 4$/.test(cmd)){this.flags.balance=true;return reply('You set the dial to four remaining marks. The tray balances and the shutter lifts, revealing the coin-shaped lock.','success');}return reply('The shutter stays closed. The dial accepts 0 through 9; work out the remaining burden from the cargo ledger.');}
 if(/^(use|insert|open) /.test(cmd)&&this.room==='cabin'){const noun=cmd.replace(/^(use|insert|open) /,'').split(/ (?:on|in|into|to|at|with) /)[0];const id=this.identify(noun);if(id==='weight'){if(!this.inventory.includes('weight'))return reply('You are not carrying the brass counterweight.');if(this.flags.weight)return reply('The counterweight is already on the tray.');this.flags.weight=true;return reply('You place the three-mark counterweight on the small chest’s tray. Now set the balance dial using the cargo ledger.','success');}if((id==='doubloon'||cmd==='open chest')&&!this.flags.balance)return reply('A shutter covers the coin lock. Balance the small chest’s tray first. The cargo ledger is in the sail loft.');}
 if(/^(examine|inspect|x|read|look at) /.test(cmd)){const noun=cmd.replace(/^(examine|inspect|x|read|look at) /,'');if(this.room==='chart'&&/compass|verse|wheels|door/.test(noun))return reply('“First face the rising sun; next seek the pole star; last watch the setting sun.” Set the three wheels with “set compass [three directions]”.');if(this.room==='tide'&&/placard|valves|engine|gauge/.test(noun))return reply(this.flags.tide?'The engine is vented; the gauge reads green.':'“Night draws the tide. The sailor holds it. Dawn sends it onward.” Valves: moon, anchor, sun. Correct valves stay in position until a mistake resets them.');if(this.room==='bells'&&/bells|cable|pitch/.test(noun))return reply('Bell 1: middle. Bell 2: low. Bell 3: high. The well’s carving shows three waves ascending.');if(this.room==='well'&&/grille|waves|carving|flute/.test(noun)&&!this.flags.bells)return reply('The flute is trapped behind a grille. “Let the bells climb as the sea climbs.” Three waves ascend from small to tall. The bell alcove is north.');if(this.room==='loft'&&/ledger|desk|cargo/.test(noun))return reply('“Chest and jewels: seven marks. Brass counterweight: three marks. Set the dial to the burden remaining after the counterweight takes its share.”');if(this.room==='cabin'&&/balance|tray|dial|shutter|chest|lock/.test(noun))return reply(this.flags.balance?'The balance is steady. The shutter has uncovered a coin-shaped lock.':'A separate tray guards the small jewel chest. Place its brass counterweight, then set its 0–9 dial to the remaining burden. Read the ledger in the sail loft to the east. Leave Willy’s gold alone.');}
 if(/^(take|get|grab|pick up) (?:the )?(?:flute|bone flute)$/.test(cmd)&&this.room==='well'&&!this.flags.bells)return reply('The bone flute is behind the grille. Solve the bell melody in the alcove to the north.');
 return null;}
 run(raw){let cmd=String(raw).trim().toLowerCase().replace(/[.!?]+$/,'').replace(/\s+/g,' ');if(!cmd)return {lines:[],kind:'system'};this.history.push(raw.trim());let lines=[],kind='normal',heading=false;
 if(this.level==='medium'){const response=this.mediumCommand(cmd);if(response)return response;}
 const alias={n:'north',s:'south',e:'east',w:'west',u:'up',d:'down'};let dir=alias[cmd]||cmd.replace(/^(go|walk|move|head) /,'');dir=alias[dir]||dir;if(dir==='down'&&(this.room==='attic'||this.room==='shack'))dir='south';if(dir==='up'&&(this.room==='street'||this.room==='cellar'))dir='north';
 if(['north','south','east','west','up','down'].includes(dir)){
 let to=this.current().exits[dir];if(!to)lines=['You cannot go that way. Exits here: '+Object.keys(this.current().exits).join(', ')+'.'];
 else if(this.room==='shack'&&to==='cellar'&&!this.flags.hatch)lines=['The hatch is nailed shut. You need something to pry it open.'];
 else if(this.room==='cellar'&&to==='tunnel'&&!this.flags.sun)lines=['A stone slab blocks the passage. The skull carving has a sun-shaped recess.'];
 else if(this.level==='medium'&&this.room==='chart'&&to==='tide'&&!this.flags.compass)lines=['The northern door is locked by three compass wheels. Read the navigator’s verse.'];
 else if(this.level==='medium'&&this.room==='pipes'&&to==='organ'&&!this.flags.tide)lines=['Scalding steam blocks the arch. Find the tideworks beyond the chart room and vent the engine.'];
 else if(to==='tunnel'&&!this.flags.light)lines=['The tunnel is pitch black. Turn on a flashlight before you enter.'];
 else if(this.room==='organ'&&to==='bridge'&&!this.flags.organ)lines=['The stone door holds fast. Wake the organ and play the right notes.'];
 else if(this.room==='bridge'&&to==='lagoon'&&!this.flags.rope)lines=['The gap is too wide to jump. The iron ring could anchor a rope.'];
 else{this.room=to;this.visited.add(to);this.moves++;heading=true;lines=this.describe();if(to==='beach'&&this.inventory.includes('treasure')&&!this.won){this.won=true;kind='victory';lines=['You spill the jewels into your father’s hands. Rubies. Sapphires. More than enough to save every house on the Goon Docks.\n\nMikey laughs. Chunk hugs Sloth. Data promises the next adventure will involve fewer plumbing accidents. Mouth, for once, has nothing to say.\n\nBeyond the breakers, the Inferno sails into the sunlight. You raise a hand to One-Eyed Willy. A deal is a deal.','YOU SAVED THE GOON DOCKS!\n'+this.visited.size+' of '+Object.keys(this.rooms).length+' locations discovered · '+this.moves+' moves'+(this.inventory.includes('emerald')?' · Bonus emerald found':''),'Keep exploring, or choose New adventure to play again.'];}}
 }else if(['look','l'].includes(cmd)){heading=true;lines=this.describe();}
 else if(['inventory','i','inv','backpack'].includes(cmd))lines=[this.inventory.length?'You carry: '+this.inventory.map(i=>items[i].name).join(', ')+'.':'Your backpack is empty.'];
 else if(cmd==='help'||cmd==='commands')lines=['MOVEMENT\ngo north / south / east / west · n / s / e / w','EXPLORATION\nlook · take map · take all · examine medallion · read map','PUZZLES\nuse crowbar · use medallion · use flashlight · use flute · play C E G · use rope · use doubloon','COMPANY\ntalk · talk Mikey · hint · inventory','Use the direction buttons or shortcuts below. Press ↑ / ↓ in the command box to recall commands.'];
 else if(cmd==='hint'){kind='system';lines=[this.hint()];}
 else if(/^(take|get|pick up|grab) /.test(cmd)){
 let noun=cmd.replace(/^(take|get|pick up|grab) /,'');const ids=noun==='all'?this.visibleItems():[this.identify(noun)];for(const id of ids){if(!id){lines.push('You don’t see that here. Type “look” to check your surroundings.');continue;}if(this.inventory.includes(id))lines.push('You already have the '+items[id].name+'.');else if(!this.visibleItems().includes(id))lines.push(id==='treasure'&&this.room==='cabin'?'The chest is locked. Its slot is shaped like a pirate coin.':'There is no '+items[id].name+' here.');else{this.inventory.push(id);this.taken.add(id);lines.push('Taken: '+items[id].name+'.');}}if(!ids.length)lines=['There is nothing loose to take here.'];
 }else if(/^(examine|inspect|x|read|look at) /.test(cmd)){
 const noun=cmd.replace(/^(examine|inspect|x|read|look at) /,'');const id=this.identify(noun);if(id&&this.available(id))lines=[items[id].description];else if(/inscription|wall|desk|painting/.test(noun)&&this.room==='chart')lines=['“When bones sing, climb from C to E to G. Then cross without touching the sea.”'];else if(/organ|keys|socket/.test(noun)&&this.room==='organ')lines=['A flute-shaped socket sits above keys marked C, E, and G. The chart room inscription might tell you what to play.'];else if(/chest|lock|gold|scales|willy/.test(noun)&&this.room==='cabin')lines=['The small chest has a coin-shaped lock. Leave the gold on the balance alone; the ship depends on it.'];else if(/hatch|floor/.test(noun)&&this.room==='shack')lines=[this.flags.hatch?'The hatch is open. Go south to descend.':'Nails hold the hatch shut. A crowbar would help.'];else if(/skull|carving|sun/.test(noun)&&this.room==='cellar')lines=['A sun-shaped recess sits inside the skull. “The sun admits the sailor.”'];else if(/gap|ring|post|crossing/.test(noun)&&this.room==='bridge')lines=['Tie a rope between the iron ring and the far post to cross safely.'];else if(noun==='room')lines=this.describe();else lines=['You cannot inspect that here. Try “look”, or examine an item in your backpack.'];
 }else if(/^(use|insert|tie|turn on|switch on|light|open) /.test(cmd)){
 let noun=cmd.replace(/^(use|insert|tie|turn on|switch on|light|open) /,'').split(/ (?:on|in|into|to|at|with) /)[0];let id=this.identify(noun);if(cmd==='open hatch')id='crowbar';if(cmd==='open chest')id='doubloon';if(!id)lines=['Try “use” followed by an item you carry, such as “use crowbar”.'];else if(!this.inventory.includes(id))lines=['You are not carrying the '+items[id].name+'.'];else if(id==='flashlight'){this.flags.light=true;lines=['You click on Data’s flashlight. A steady beam cuts through the dark.'];}else{const uses={crowbar:{room:'shack',flag:'hatch',text:'You lever the hatch upward. Nails squeal. Below, stone steps disappear into a hidden cellar. The way south is open.'},medallion:{room:'cellar',flag:'sun',text:'The sun medallion fits the skull. You twist it, and the stone slab slides aside. Cold sea air rushes from the southern passage.'},flute:{room:'organ',flag:'flute',text:'You set the bone flute into its socket. Air hums through the organ. The keys wake under Andy’s fingers. Now play the right notes.'},rope:{room:'bridge',flag:'rope',text:'Data hooks the rope over the far post. You tie it to the iron ring and test the knot. A safe crossing stretches south.'},doubloon:{room:'cabin',flag:'chest',text:'Willy’s coin turns in the lock. The chest opens, revealing a pouch of jewels. Mikey grins. “That’s our ticket home.”'}};const u=uses[id];if(u&&this.room===u.room){if(this.flags[u.flag])lines=['You have already done that.'];else{this.flags[u.flag]=true;lines=[u.text];kind='success';}}else if(id==='map')lines=[items.map.description];else lines=['The '+items[id].name+' has no use here. Look around for somewhere it might fit.'];}
 }else if(/^play\b/.test(cmd)){
 if(this.room!=='organ')lines=['There is no instrument to play here.'];else if(!this.flags.flute)lines=['The organ is silent. Its flute-shaped socket is empty.'];else if(this.flags.organ)lines=['The door is already open. Andy wisely leaves the keys alone.'];else if(cmd.replace(/^play\s*/, '').replace(/[ ,\-]/g,'')==='ceg'){this.flags.organ=true;kind='success';lines=['C. E. G.\nThe last note rolls through the mountain. Bones tremble, gears turn, and the stone door opens to the south. Andy bows. “No encore.”'];}else lines=['A sour chord rattles the bones. The door stays shut. Try the three notes carved in the chart room.'];
 }else if(/^talk\b/.test(cmd)){
 const person=cmd.replace(/^talk(?: to)?\s*/, '');if(person&&!['mikey','mouth','data','chunk','andy','sloth'].includes(person))lines=['Your companions are Mikey, Mouth, Data, Chunk, and Andy. Sloth joins you near the ship.'];else if(person==='sloth'&&!['deck','cabin','beach'].includes(this.room))lines=['Sloth hasn’t caught up with the gang yet.'];else{const voices={mikey:'Mikey: “We’ve got one chance. Follow the clues, and stick together.”',mouth:'Mouth: “I can translate pirate. Sarcasm is basically a related language.”',data:'Data: “Everything in my backpack works. Eventually.”',chunk:'Chunk: “If we find treasure, can we stop for pizza?”',andy:'Andy: “Three notes. Check that old inscription before we touch the keys.”',sloth:'Sloth: “Friends! Go get treasure!”'};lines=[voices[person||({attic:'mikey',shack:'chunk',pipes:'data',organ:'andy',deck:'sloth'}[this.room]||'mouth')]];}
 }else if(cmd==='map')lines=['Your discovery map is beside the adventure (below it on a phone). Gold marks your current room. Only places you have visited are revealed.'];
 else if(/gold|scales/.test(cmd)&&this.room==='cabin')lines=['Mikey catches your hand. “Leave Willy’s gold. Take only the jewels from the small chest.”'];
 else lines=['That command stumps the gang. Try “look”, “take [item]”, “use [item]”, or a direction. Type “help” for examples.'];
 return {lines,kind,heading,room:this.room};
 }
 snapshot(){return {level:this.level,room:this.room,location:this.current().name,visited:[...this.visited],inventory:this.inventory.map(i=>items[i].name),flags:{...this.flags},moves:this.moves,won:this.won};}
 save(){return {level:this.level,room:this.room,visited:[...this.visited],inventory:[...this.inventory],taken:[...this.taken],flags:{...this.flags},moves:this.moves,won:this.won,history:[...this.history],hints:{...this.hints},transcript:this.transcript};}
 static restore(data,level){const g=new Game(level);if(!data||data.level!==g.level||!g.rooms[data.room]||!Array.isArray(data.visited)||!Array.isArray(data.inventory)||!Array.isArray(data.taken))return g;g.room=data.room;g.visited=new Set(data.visited.filter(id=>g.rooms[id]));g.visited.add(g.room);g.inventory=[...new Set(data.inventory.filter(id=>items[id]&&!id.startsWith('s_')&&(g.level==='medium'||id!=='weight')))];g.taken=new Set(data.taken.filter(id=>items[id]));g.inventory.forEach(id=>g.taken.add(id));g.flags=data.flags&&typeof data.flags==='object'?{...data.flags}:{};g.moves=Number.isSafeInteger(data.moves)&&data.moves>=0?data.moves:0;g.won=data.won===true;g.history=Array.isArray(data.history)?data.history.filter(s=>typeof s==='string'):[];g.hints=data.hints&&typeof data.hints==='object'?{...data.hints}:{};g.transcript=Array.isArray(data.transcript)?data.transcript.filter(t=>t&&Array.isArray(t.result?.lines)&&t.result.lines.every(s=>typeof s==='string')&&g.rooms[t.result.room]):[];return g;}
}
root.Adventure={Game,rooms,mediumRooms,items};if(typeof module!=='undefined')module.exports=root.Adventure;
})(typeof window!=='undefined'?window:globalThis);
