(function(root){
'use strict';
const A=root.Adventure||(typeof require==='function'?require('./engine.js'):null);
const rooms={
 s_room:{name:'Sloth’s first room of his own',short:'Your room',x:0,y:0,chapter:1,area:'A NEW START',description:'Sunlight. An unlocked door. A bed that does not come with a chain. You are Sloth, staying with Chunk’s family, and today you are going into town on your own.\n\nChunk has left a shopping list and a bus pass on the dresser. His note says: “Breakfast first. Bus 3 goes downtown. The groceries are already paid for. Meet us by the wharf!” You tuck in your Superman shirt. Big day.',exits:{south:'s_kitchen'},items:['s_list','s_pass']},
 s_kitchen:{name:'The toast incident',short:'Kitchen',x:0,y:1,chapter:1,area:'A NEW START',description:'The toaster has three settings: 1 PALE, 2 GOLDEN, 3 VOLCANIC. Last night, Chunk called setting three “a cry for help.”\n\nA note says: “Turn the dial to golden, then make toast.” The kitchen radio announces good weather. You announce good breakfast. Commands: “set toaster [1–3]”, then “make toast”.',exits:{north:'s_room',east:'s_porch'},items:['s_toast']},
 s_porch:{name:'The screen-door negotiation',short:'Front porch',x:1,y:1,chapter:1,area:'A NEW START',description:'A screen door keeps bouncing shut while you carry breakfast. You have discovered a formidable new opponent: a spring hinge.\n\nA doorstop sits on the porch rail. Chunk’s mother has put out a clean scarf for you. “You can always ask for help,” she says. “And you can always say no.” The bus stop is east. Use the doorstop here to prop the screen door.',exits:{west:'s_kitchen',east:'s_stop'},items:['s_doorstop','s_scarf']},
 s_stop:{name:'The bus-stop adventure',short:'Bus stop',x:2,y:1,chapter:1,area:'A NEW START',description:'The bus shelter promises 3 DOWNTOWN and 8 AQUARIUM. You briefly consider becoming mayor of the aquarium. Today, your friends need you downtown.\n\nThe driver is patient. “Pass first, then tell me the route.” Use your bus pass, then “board bus [number]”. The south exit is the downtown bus ride.',exits:{west:'s_porch',south:'s_square'},items:[]},
 s_square:{name:'Downtown, slightly sideways',short:'Town square',x:2,y:2,chapter:2,area:'LIFE IN ASTORIA',description:'A parking meter eats somebody’s coin. You offer it toast. Its refusal is very rude.\n\nA notice points west to the library and east to the market. The picnic green is south. A worried note from Mikey is pinned to a bench: “Fratellis back. Follow us to the wharf. If something goes wrong, get help.”',exits:{north:'s_stop',west:'s_library',east:'s_market',south:'s_picnic'},items:[]},
 s_library:{name:'The very quiet library',short:'Library',x:1,y:2,chapter:2,area:'LIFE IN ASTORIA',description:'Your first whisper turns a page three tables away. The librarian smiles and offers a practice whisper. You try again. Much better.\n\nOn the local-history shelf is a pump manual for the old Fratelli warehouse. It says: “To drain the lower passage, turn the wheel RIGHT, RIGHT, LEFT. Never force a flooded door.” You may borrow the manual; the librarian adds a bookmark shaped like a giant ear.',exits:{east:'s_square'},items:['s_manual']},
 s_market:{name:'Groceries and other emergencies',short:'Market',x:3,y:2,chapter:2,area:'LIFE IN ASTORIA',description:'You ask where the chocolate lives. The grocer points at aisle two, which is excellent urban planning.\n\nChunk prepaid his shopping list: flour, chocolate, and the bolt cutters Data ordered for a broken bicycle lock. Show the list with “use shopping list” to collect the order. A walkway leads south to the wharf.',exits:{west:'s_square',south:'s_wharf'},items:['s_flour','s_chocolate','s_cutters']},
 s_wharf:{name:'Something fishy at the wharf',short:'Wharf',x:3,y:3,chapter:2,area:'FRIENDS NEED HELP',description:'The Goonies’ bikes lie beside an abandoned fish warehouse. You hear Chunk calling from inside. Mama Fratelli and your brothers have caught your friends spying on their latest scheme: forged deeds to steal houses in the Goon Docks.\n\nA cargo rope hangs from a bollard. To the east, an alley skirts the warehouse. You decide that today’s biggest grown-up skill is choosing your own family.',exits:{north:'s_market',east:'s_alley',west:'s_picnic'},items:['s_rope']},
 s_alley:{name:'The brothers’ grand plan',short:'Fish alley',x:4,y:3,chapter:3,area:'THE FRATELLI WAREHOUSE',description:'Jake and Francis are arguing about who is the criminal mastermind. Neither has noticed the EXIT sign pointing at a wall.\n\nThe warehouse passage to the north is flooded. A pump shed stands south. The sheriff’s station is east. Above the alley, a cargo net hangs beside a flour hopper on the roof. Nobody gets hurt if the net drops; plenty of dignity might.',exits:{west:'s_wharf',north:'s_hideout',south:'s_pump',east:'s_station'},items:[]},
 s_pump:{name:'The stubborn pump wheel',short:'Pump shed',x:4,y:4,chapter:3,area:'THE FRATELLI WAREHOUSE',description:'A steel wheel controls the flooded warehouse passage. You could bend it. You could also read the manual, which seems cheaper for everybody.\n\nTry “turn wheel [three directions]”, using right or left. A wrong sequence resets safely. A ladder leads east to the warehouse roof.',exits:{north:'s_alley',east:'s_roof'},items:[]},
 s_hideout:{name:'No more basement rules',short:'Warehouse',x:4,y:2,chapter:3,area:'THE FRATELLI WAREHOUSE',description:'Your friends are behind a chained gate. Mama stands beside a desk full of forged deeds. “You belong downstairs,” she snaps.\n\nYou stand tall. That rule is finished. Free the gang with your bolt cutters, then “confront mama”. A fraud ledger on the desk can put the whole family’s scheme in front of the sheriff.',exits:{south:'s_alley'},items:['s_ledger']},
 s_roof:{name:'Operation Flour Power',short:'Cargo roof',x:5,y:4,chapter:3,area:'THE FRATELLI WAREHOUSE',description:'The flour hopper points into the alley. A cargo net can be lowered with a rope. You have watched enough superhero television to recognize a perfectly good finale.\n\nPrepare the hopper with flour and rig the cargo rope. Once your friends are free, “shout hey you guys” will draw the brothers under the net. “Pull rope” finishes the prank. A stairway leads north to the sheriff’s station.',exits:{west:'s_pump',north:'s_station'},items:[]},
 s_station:{name:'The sheriff meets the family',short:'Sheriff',x:5,y:3,chapter:4,area:'A BETTER KIND OF FAMILY',description:'The sheriff listens. You do not have to be the loudest person in the room to be believed.\n\nShow the fraud ledger with “show ledger”. With your friends safe, your brothers contained, and Mama confronted, the sheriff can arrest the Fratellis. Your job is to bring evidence; the deputies handle the handcuffs.',exits:{west:'s_alley',south:'s_roof'},items:[]},
 s_picnic:{name:'A seat at the picnic',short:'Picnic green',x:2,y:3,chapter:4,area:'A BETTER KIND OF FAMILY',description:'A picnic table waits under the trees. There is a chair for you, a real one with no locks attached. Chunk has reserved the largest sandwich.\n\nOnce your friends are safe and the sheriff has dealt with the Fratellis, come here to celebrate your first day on your own terms.',exits:{north:'s_square',east:'s_wharf'},items:[]}
};
const items={
 s_list:{name:'shopping list',aliases:['shopping list','list'],description:'Prepaid by Chunk: flour, chocolate, and Data’s bolt cutters. Bus 3 goes downtown. Show the list to the grocer with “use shopping list”.'},
 s_pass:{name:'bus pass',aliases:['bus pass','pass'],description:'An all-day bus pass. Use it at the stop before boarding. Chunk’s list says which route goes downtown.'},
 s_toast:{name:'golden toast',aliases:['golden toast','toast','breakfast'],description:'Breakfast made by you. A small victory that tastes better than the toaster’s volcanic option.'},
 s_doorstop:{name:'doorstop',aliases:['doorstop','door stop'],description:'A rubber wedge. An easier way to beat the screen door than taking it off its hinges.'},
 s_scarf:{name:'clean scarf',aliases:['clean scarf','scarf'],description:'A bright scarf from Chunk’s mother. Yours to wear. Nobody gets to choose your clothes for you.'},
 s_manual:{name:'pump manual',aliases:['pump manual','manual','book'],description:'Warehouse drain sequence: RIGHT, RIGHT, LEFT. At the pump shed, type “turn wheel right right left”.'},
 s_flour:{name:'bag of flour',aliases:['bag of flour','flour'],description:'Good for baking. Also good for the roof’s old flour hopper. The brothers could use a dusting of humility.'},
 s_chocolate:{name:'chocolate bar',aliases:['chocolate bar','chocolate','candy'],description:'A chocolate bar to share with Chunk after the rescue. Friendship tastes pretty good.'},
 s_cutters:{name:'bolt cutters',aliases:['bolt cutters','cutters'],description:'Data’s bicycle tools. They can cut the gate chain without putting your friends at risk.'},
 s_rope:{name:'cargo rope',aliases:['cargo rope','rope'],description:'A strong cargo rope. Rig it on the warehouse roof to lower the net over the alley.'},
 s_ledger:{name:'fraud ledger',aliases:['fraud ledger','ledger','evidence','deeds'],description:'Mama’s record of forged deeds, stolen house payments, and the brothers’ deliveries. Bring it to the sheriff. This is evidence, not a souvenir.'}
};
Object.assign(A.items,items);
class SlothGame extends A.Game{
 constructor(){super();this.level='sloth';this.rooms=rooms;this.room='s_room';this.visited=new Set(['s_room']);}
 identify(noun){noun=noun.replace(/^(the|a|an) /,'').trim();return Object.keys(items).find(id=>items[id].aliases.includes(noun));}
 visibleItems(){return this.current().items.filter(id=>!this.taken.has(id)&&(id!=='s_toast'||this.flags.toast)&&(!['s_flour','s_chocolate','s_cutters'].includes(id)||this.flags.order)&&(id!=='s_ledger'||(this.flags.rescue&&this.flags.boundary)));}
 describe(){const lines=super.describe();if(this.room==='s_hideout'&&this.flags.rescue)lines[0]=lines[0].replace('Your friends are behind a chained gate.','The gate is open and your friends are safe outside.').replace('Free the gang with your bolt cutters, then “confront mama”.','You can stand up to Mama with “confront mama”.');if(this.room==='s_hideout'&&this.flags.boundary)lines[0]=lines[0].replace('Mama stands beside a desk full of forged deeds. “You belong downstairs,” she snaps.','Mama has backed away from the desk. You have made your boundary clear.');if(this.room==='s_hideout'&&this.flags.arrest)lines[0]='The warehouse is quiet. Your friends are free, and the Fratellis are in custody. Deputies are collecting the remaining forged deeds. You can leave whenever you choose.';if(this.room==='s_alley'&&this.flags.brothers)lines[0]=lines[0].replace('Jake and Francis are arguing about who is the criminal mastermind. Neither has noticed the EXIT sign pointing at a wall.','Jake and Francis are tangled in a cargo net, disputing whose fault it is. A puff of flour settles on their matching scowls.');if(this.room==='s_alley'&&this.flags.arrest)lines[0]='The alley is quiet. The deputies have taken your brothers away, and the empty cargo net flaps in the breeze. The flour left on the pavement looks suspiciously like two defeated masterminds.';const status={s_kitchen:this.flags.toast?'Your golden toast is ready. Breakfast: handled.':null,s_porch:this.flags.door?'The doorstop is holding the screen door open.':null,s_stop:this.flags.bus?'Your downtown ride is ready. Go south.':null,s_pump:this.flags.drain?'The passage is drained. The wheel is safely locked.':null,s_hideout:this.flags.rescue?'The gate is open. The Goonies are safely outside.':null,s_roof:this.flags.brothers?'Jake and Francis are safely tangled in the net below.':null,s_station:this.flags.arrest?'Mama, Jake, and Francis are in custody. You can meet your friends at the picnic green.':null};if(status[this.room])lines.splice(1,0,status[this.room]);return lines;}
 hint(){if(this.won)return 'You finished Sloth’s adventure! Explore any missed places or start this mode again.';const steps=[
 ['supplies',this.inventory.includes('s_list')&&this.inventory.includes('s_pass'),['Chunk left two useful things in your room.','Take the shopping list and bus pass. “Take all” collects both.']],
 ['breakfast',this.flags.toast,['The toaster labels tell you which setting makes good breakfast.','In the kitchen: “set toaster 2”, then “make toast”. Take the toast if you want to bring it.']],
 ['door',this.flags.door,['The screen door needs a small wedge, not a superhero punch.','On the porch: “take doorstop”, then “use doorstop”.']],
 ['bus',this.flags.bus,['Chunk’s note names the downtown bus. The driver needs your pass first.','At the stop: “use bus pass”, then “board bus 3”. Go south.']],
 ['order',this.flags.order,['Your shopping order is prepaid. Find the market east of the square.','At the market: “use shopping list”, then “take all”.']],
 ['tools',this.inventory.includes('s_cutters')&&this.inventory.includes('s_flour'),['Collect the groceries and tools before heading to the warehouse.','At the market, “take all” picks up the flour and bolt cutters.']],
 ['drain',this.flags.drain,['The library’s old pump manual explains how to drain the warehouse passage.','At the pump shed south of the fish alley: “turn wheel right right left”.']],
 ['rescue',this.flags.rescue,['The warehouse is north of the alley after the water is drained. Free your friends.','In the warehouse: “use bolt cutters”.']],
 ['boundary',this.flags.boundary,['You are free to set your own rules. Tell Mama this treatment is over.','In the warehouse, type “confront mama”.']],
 ['ledger',this.inventory.includes('s_ledger'),['The sheriff needs evidence of Mama’s property scheme.','Take the fraud ledger from the warehouse desk after confronting Mama.']],
 ['rope',this.inventory.includes('s_rope'),['A net on the warehouse roof needs its cargo rope.','Take the cargo rope at the wharf. The roof is east of the pump shed.']],
 ['prank',this.flags.flour&&this.flags.net,['Prepare the roof’s flour hopper and cargo net before calling the brothers.','On the roof: “use flour”, then “use cargo rope”.']],
 ['brothers',this.flags.brothers,['Get the brothers under the net, then let gravity finish your prank.','On the roof: “shout hey you guys”, then “pull rope”.']],
 ['arrest',this.flags.arrest,['Your friends are safe. Let the sheriff handle the arrests.','At the sheriff’s station, type “show ledger”.']]
 ];const step=steps.find(s=>!s[1]);if(!step)return 'Go to the picnic green, south of the town square or west of the wharf, to finish your adventure.';const n=this.hints[step[0]]||0;this.hints[step[0]]=n+1;return 'SLOTH HINT '+Math.min(n+1,2)+' / 2\n'+step[2][Math.min(n,1)];}
 run(raw){const cmd=String(raw).trim().toLowerCase().replace(/[.!?]+$/,'').replace(/\s+/g,' ');const result=(text,kind='normal',heading=false)=>{this.history.push(String(raw).trim());return {lines:Array.isArray(text)?text:[text],kind,heading,room:this.room};};
 const aliases={n:'north',s:'south',e:'east',w:'west'};let dir=cmd.replace(/^(go|walk|move|head) /,'');dir=aliases[dir]||dir;
 if(['north','south','east','west'].includes(dir)){const next=this.current().exits[dir];if(!next)return result('You cannot go that way. Exits: '+Object.keys(this.current().exits).join(', ')+'.');if(this.room==='s_porch'&&next==='s_stop'&&!this.flags.door)return result('The screen door swings shut. Prop it with the doorstop before heading out.');if(this.room==='s_stop'&&next==='s_square'&&!this.flags.bus)return result('Show your pass and choose the downtown bus before riding south.');if(this.room==='s_alley'&&next==='s_hideout'&&!this.flags.drain)return result('The passage is flooded. Use the pump shed south of the alley to drain it safely.');this.room=next;this.visited.add(next);this.moves++;if(next==='s_picnic'&&this.flags.arrest&&!this.won){this.won=true;return result(['SLOTH SAVES THE DAY!\n\nYour friends are free. Mama and your brothers are under arrest for kidnapping and fraud. The stolen deeds will be returned. The sheriff says nobody is taking you back to a locked basement.','Jake and Francis insist the flour-covered cargo net was “an elaborate ambush.” Mama demands a lawyer. The deputies provide one, along with three extremely unflattering booking photographs.','At the picnic, Chunk makes room beside him. You share a sandwich'+(this.flags.shared?' and the last piece of chocolate':'')+'. Mikey asks what you want to do tomorrow.\n\nYou think it over. “Something I choose.”\n\nA room of your own. Friends who listen. And a whole town of new things to try.','YOUR FIRST DAY, YOUR OWN WAY\n'+this.visited.size+' of '+Object.keys(rooms).length+' locations · '+this.moves+' moves'+(this.flags.scarf?' · Scarf looking excellent':''),'Keep exploring or start a new Sloth adventure.'],'victory',true);}return result(this.describe(),'normal',true);}
 if(cmd==='help'||cmd==='commands')return result(['You play as Sloth in an original side story. Solve everyday mishaps, rescue the Goonies, and bring the Fratellis to justice.','EXPLORE\nlook · take all · examine [item] · read manual · inventory · talk · hint · north / south / east / west','EVERYDAY LIFE\nset toaster [1–3] · make toast · use doorstop · use bus pass · board bus [number] · use shopping list · wear scarf','THE RESCUE\nturn wheel [right/left, three directions] · use bolt cutters · confront mama · take ledger','THE COMEUPPANCE\nuse flour · use cargo rope · shout hey you guys · pull rope · show ledger','EXTRAS\neat toast · share chocolate. Repeat “hint” for stronger help. Wrong attempts never cause harm.'],'system');
 if(/^set toaster\b/.test(cmd)){if(this.room!=='s_kitchen')return result('The toaster is in Chunk’s kitchen.');if(!/^set toaster [123]$/.test(cmd))return result('Use “set toaster” with 1, 2, or 3.');this.flags.toaster=Number(cmd.slice(-1));return result('You set the toaster to '+['','pale','golden','volcanic'][this.flags.toaster]+'. Now try “make toast”.');}
 if(cmd==='make toast'){if(this.room!=='s_kitchen')return result('You need the kitchen toaster.');if(this.flags.toast)return result('You already made breakfast. The toaster has earned a rest.');if(this.flags.toaster!==2)return result(this.flags.toaster===3?'The toaster produces two charcoal rectangles and a tiny smoke cloud. You unplug it, clear the crumbs, and try again. Setting GOLDEN looks promising.':'The bread is still pale. Try the setting marked GOLDEN.');this.flags.toast=true;return result('Pop! Golden toast. You bow to an audience of one delighted kitchen radio. Breakfast is ready to take.','success');}
 if(/^board(?: bus)?\b/.test(cmd)){if(this.room!=='s_stop')return result('Board the bus at the bus stop.');if(!this.flags.pass)return result('The driver asks for your bus pass first.');if(!/^board(?: bus)? 3$/.test(cmd))return result('That route does not go downtown. The driver helps you check Chunk’s note before you leave.');this.flags.bus=true;return result('Bus 3 it is. The driver saves you a roomy seat. Downtown is now one southward ride away.','success');}
 if(/^turn wheel\b/.test(cmd)){if(this.room!=='s_pump')return result('The drain wheel is in the pump shed.');if(this.flags.drain)return result('The water is already drained. No need to force the wheel.');if(cmd.replace(/[,\-]/g,' ').replace(/\s+/g,' ')==='turn wheel right right left'){this.flags.drain=true;return result('Right. Right. Left. The pump thumps awake, drains the lower passage, and locks itself safely. The warehouse north of the alley is accessible.','success');}return result('The safety catch resets the wheel. Read the pump manual in the library for the three-turn sequence.');}
 if(cmd==='confront mama'||cmd==='tell mama no'){if(this.room!=='s_hideout')return result('Mama is inside the warehouse.');if(!this.flags.rescue)return result('Free your friends from the gate first. You want them safely out of reach before confronting her.');this.flags.boundary=true;return result('“No more chains. No more basement,” you tell Mama. “You do not get to hurt me or my friends.”\n\nChunk stands beside you. Mama blusters, but you keep your footing and your boundary. The fraud ledger is now within reach.','success');}
 if(/^shout\b/.test(cmd)||cmd==='call brothers'){if(this.room!=='s_roof')return result('Save the distraction for the cargo roof.');if(this.flags.brothers)return result('Your brothers are already in the net. Their complaints need no amplification.');if(!this.flags.rescue)return result('Free your friends before drawing the brothers into the alley.');if(!this.flags.flour||!this.flags.net)return result('Prepare the flour hopper and rig the cargo rope before you call them.');this.flags.lured=true;return result('“Hey, you guys!”\n\nJake and Francis charge into the alley. The hopper tips a puff of flour over their matching scowls. “You look ridiculous,” each tells the other. Both are directly under the cargo net. Pull the rope!');}
 if(cmd==='pull rope'){if(this.room!=='s_roof')return result('The net’s rope is rigged on the cargo roof.');if(this.flags.brothers)return result('The net is already holding the brothers safely.');if(!this.flags.net||!this.flags.lured)return result('Rig the cargo rope and lure the brothers under the net first.');this.flags.brothers=true;return result('You lower the cargo net. Jake and Francis tumble gently into a heap of rope, flour, and wounded pride. The net holds them until the deputies arrive.\n\n“Criminal masterminds,” you announce. Chunk nearly falls over laughing.','success');}
 if(cmd==='show ledger'||cmd==='give ledger'||cmd==='show evidence'){if(this.room!=='s_station')return result('Bring the evidence to the sheriff’s station.');if(!this.inventory.includes('s_ledger'))return result('The sheriff needs the fraud ledger from the warehouse desk.');if(!this.flags.rescue||!this.flags.boundary||!this.flags.brothers)return result('The sheriff starts reading, but your friends still need protection. Finish the rescue, stand up to Mama, and contain the brothers.');if(this.flags.arrest)return result('The Fratellis are already in custody. Go enjoy the picnic.');this.flags.arrest=true;return result('The sheriff matches the ledger to the forged deeds and calls his deputies. Your friends give their statements. Mama is arrested for kidnapping and fraud; Jake and Francis are collected from their flour-dusted net.\n\n“No private dungeon. No stolen homes. No more bullying,” the sheriff says. You are free to meet your chosen family at the picnic green.','success');}
 if(/^(use|wear|eat|share|give) /.test(cmd)){let noun=cmd.replace(/^(use|wear|eat|share|give) /,'').split(/ (?:on|with|to|at) /)[0];const id=this.identify(noun);if(!id)return result('Try an item from your backpack, such as “use doorstop” or “use bolt cutters”.');if(!this.inventory.includes(id))return result('You are not carrying the '+items[id].name+'.');const uses={s_doorstop:{room:'s_porch',flag:'door',text:'You wedge the screen door open. A tiny piece of rubber wins a battle you were about to solve with a refrigerator. The way east is clear.'},s_pass:{room:'s_stop',flag:'pass',text:'The driver checks your pass and nods. Now choose a route with “board bus [number]”.'},s_list:{room:'s_market',flag:'order',text:'The grocer reads Chunk’s prepaid list and sets out flour, chocolate, and bolt cutters. You were expecting one bag. You receive a small quest. Take the order.'},s_cutters:{room:'s_hideout',flag:'rescue',text:'You cut the gate chain and swing it open. Chunk hugs you. Data checks everyone for injuries. Mikey leads the gang outside to safety.\n\nYou helped your friends. Now it is time to tell Mama the basement rules are over.'},s_flour:{room:'s_roof',flag:'flour',text:'You fill the hopper with flour. The brothers’ evil catering business is about to discover an entirely new kind of breading.'},s_rope:{room:'s_roof',flag:'net',text:'You rig the cargo rope and test the net. It will lower safely over the alley and hold the brothers until the deputies arrive.'}};const u=uses[id];if(u){if(this.room!==u.room)return result('The '+items[id].name+' has no use here.');if(this.flags[u.flag])return result('You already did that.');this.flags[u.flag]=true;return result(u.text,'success');}if(id==='s_scarf'){this.flags.scarf=true;return result('You tie on your scarf. The mirror, if it were here, would have excellent news.');}if(id==='s_toast')return result('You enjoy your golden toast. Master chef? Maybe. Master of breakfast? Absolutely.');if(id==='s_chocolate'){if(!this.flags.rescue)return result('Save some chocolate to share with Chunk when your friends are safe.');this.flags.shared=true;return result('You split the chocolate with Chunk. He calls it a celebration; you call it good planning.');}if(id==='s_ledger')return result('Take the ledger to the sheriff and type “show ledger”.');if(id==='s_manual')return result(items[id].description);}
 if(/^talk\b/.test(cmd)){const dialogue={s_kitchen:'Chunk’s mother: “Try the golden setting. And if you burn it, bread is allowed to have a second chance.”',s_porch:'Chunk’s mother: “That doorstop is for you. You can ask for help whenever you want.”',s_stop:'Driver: “Chunk’s note has your route. Take your time; nobody has to rush.”',s_library:'Librarian: “Everybody learns the quiet voice. Mine took years.”',s_market:'Grocer: “Show me the prepaid list. Then collect your order.”',s_hideout:this.flags.rescue?'Chunk: “You came for us. Now we’re here for you.”':'Chunk: “Sloth! The chain on this gate is the only thing keeping us in!”',s_roof:'Data: “The net will hold them safely. The embarrassment may last longer.”',s_station:'Sheriff: “Bring the ledger. I’ll handle the arrests.”',s_picnic:'Mikey: “You always have a place with us. What do you want to do next?”'};return result(dialogue[this.room]||'You straighten your Superman shirt. “Friends first. Then the rest.”');}
 if(/^(read|examine|inspect|x|look at) (?:the )?(note|toaster|dial|door|sign|routes|wheel|net|hopper|gate|mama)$/.test(cmd))return result(this.current().description);
 return super.run(raw);
 }
 static restore(data){const g=new SlothGame();if(!data||data.level!=='sloth'||!rooms[data.room]||!Array.isArray(data.visited)||!Array.isArray(data.inventory))return g;g.room=data.room;g.visited=new Set(data.visited.filter(id=>rooms[id]));g.visited.add(g.room);g.inventory=[...new Set(data.inventory.filter(id=>items[id]))];g.taken=new Set((Array.isArray(data.taken)?data.taken:[]).filter(id=>items[id]));g.inventory.forEach(id=>g.taken.add(id));g.flags=data.flags&&typeof data.flags==='object'?{...data.flags}:{};g.moves=Number.isSafeInteger(data.moves)&&data.moves>=0?data.moves:0;g.won=data.won===true;g.history=Array.isArray(data.history)?data.history.filter(s=>typeof s==='string'):[];g.hints=data.hints&&typeof data.hints==='object'?{...data.hints}:{};g.transcript=Array.isArray(data.transcript)?data.transcript.filter(t=>t&&Array.isArray(t.result?.lines)&&t.result.lines.every(s=>typeof s==='string')&&rooms[t.result.room]):[];return g;}
}
A.SlothGame=SlothGame;A.slothRooms=rooms;
if(typeof module!=='undefined')module.exports={SlothGame,rooms,items};
})(typeof window!=='undefined'?window:globalThis);
